name = "cloudflare-workers-wasm-argon2-example"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-01"

[build]
command = "./build-wasm.sh && node build-js.js"

[build.upload]
format = "modules"
dir = "./worker"
main = "./index.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"
